[wokwi]
version = 1
elf = '.esphome/build/atmosfera-echo-hub/.pioenvs/atmosfera-echo-hub/firmware.elf'
firmware = '.esphome/build/atmosfera-echo-hub/.pioenvs/atmosfera-echo-hub/firmware.bin'

[[net.forward]]
from = "localhost:8180"
to = "target:80"